apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: grocery-ns
type: Opaque
data:
  mongo-root-username: cm9vdA==  # base64 of 'root'
  mongo-root-password: ZXhhbXBsZQ==  # base64 of 'example'